version: '3.8'

services:
  
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

  api-1:
    build: .
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/app/app:ro
    depends_on:
      redis:
        condition: service_started
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  api-2:
    build: .
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/app/app:ro
    depends_on:
      redis:
        condition: service_started
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PAYMENTS_STREAM=payments-stream
      - PAYMENTS_CONSUMER_GROUP=payments-workers
      - WORKER_READ_COUNT=10
      - WORKER_READ_BLOCK_MS=5000
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - PYTHONUNBUFFERED=1
    command: ["poetry", "run", "python", "-m", "app.worker"]
    depends_on:
      redis:
        condition: service_started
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "50MB"

networks:
  rinha-network:
    name: rinha-network
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true

