version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments_user -d payments_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

  api-1:
    build: .
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DATABASE_URL=postgresql://payments_user:payments_password@postgres:5432/payments_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/app/app:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  api-2:
    build: .
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DATABASE_URL=postgresql://payments_user:payments_password@postgres:5432/payments_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/app/app:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

networks:
  rinha-network:
    name: rinha-network
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true

volumes:
  postgres_data:
