version: '3.8'

services:
  api-1:
    build: .
    ports:
      - "8003:8080"
    networks:
      - rinha-network

  api-2:
    build: .
    ports:
      - "8004:8080"
    networks:
      - rinha-network

networks:
  rinha-network:
    name: rinha-network
    driver: bridge
