version: '3.8'

services:
  api-1:
    build: .
    volumes:
      - ./main.py:/app/main.py:ro
    networks:
      - rinha-network

  api-2:
    build: .
    volumes:
      - ./main.py:/app/main.py:ro
    networks:
      - rinha-network

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-network

networks:
  rinha-network:
    name: rinha-network
    driver: bridge
